### ISSUE TITLE
提示更新无法使用，版本更新到7.6.3.101

### ISSUE THREAD

**Issue by brucmao** [docker-easyconnect/docker-easyconnect#156]
因为公司 easyconnect还要短信验证，没法使用cli版本

只能在win下用docker desktop 用带 VNC 服务端的7.6.3版 image，今天无法使用了，只能下载windows版本

看了当前window使用的easyconnect使用的版本是7.6.3.101
![image](https://user-images.githubusercontent.com/6119652/178939597-491d5915-9b24-4b2f-8e00-c06ca2f4acd4.png)

**Comment by brucmao** [comment]
重新打了镜像还是不行，cli版本可以登录，但是二次验证又不能输入短信

**Comment by Hagb** [comment]
> 重新打了镜像还是不行，cli版本可以登录，但是二次验证又不能输入短信

重新打镜像有没有停用缓存？

另外 vnc 7.6.3 使用的时候是不是提示版本更新？

**Comment by brucmao** [comment]
重新更新dockerhub镜像，还是提示要更新
docker image ls
REPOSITORY                          TAG       IMAGE ID       CREATED       SIZE
hagb/docker-easyconnect   7.6.3     2775012799f6   7 hours ago   515MB
fake-hwaddr                          latest    0afbe8e13f31   5 days ago    214MB
![Snipaste_2022-07-20_09-46-13](https://user-images.githubusercontent.com/6119652/179878947-db709ae9-a97a-4fb1-ace5-67c2f5538798.png)

**Comment by lichengx** [comment]
停docker后清理一下$HOME/.ecdata，然后在启动容器试一试，我是这么解决的

**Comment by brucmao** [comment]
> 停docker后清理一下$HOME/.ecdata，然后在启动容器试一试，我是这么解决的

感谢，清理后成功登录

**Comment by wkjun** [comment]
`$HOME/.ecdata/conf/easy_connect.json`
```
{
"language": "zh_CN",
"force_update": false
},
```
配置文件添加`"force_update": false` 参数试试看.

**Comment by hackstepz** [comment]
> 停docker后清理一下$HOME/.ecdata，然后在启动容器试一试，我是这么解决的

同样问题，已解决，感谢

**Comment by weihanhan** [comment]
解决方式:
方案1. 直接删除~/.ecdata文件夹下所有文件，但这样每次都需要重新填写信息。
方案2. 将~/.ecdata/conf/Version.xml文件中的版本号改成大于等于pkg_version.xml中同系列版本<force_update_le>标签下的版本号，手动改过一次之后就不会再出现提示升级的问题了。
```
<!-- 例如 Version.xml 如下，我安装的版本系列为767(7.6.7.*)-->
<?xml version="1.0" encoding="utf-8"?>
<root>
<alias>linux_767</alias>
<version>7.6.7.4</version>
<pkg>deb</pkg>
<arch>x64</arch>
</root>

<!-- 在pkg_version.xml中767的标签片段如下-->
<linux_767>
    <deb>
        <x86>
            <version>7.6.7.7</version>
            <force_update_le>7.6.7.6</force_update_le>
        </x86>
        <x64>
            <version>7.6.7.7</version>
            <force_update_le>7.6.7.6</force_update_le>
        </x64>
    </deb>
    <rpm>
        <x86>
            <version>7.6.7.7</version>
            <force_update_le>7.6.7.6</force_update_le>
        </x86>
        <x64>
            <version>7.6.7.7</version>
            <force_update_le>7.6.7.6</force_update_le>
        </x64>
    </rpm>
</linux_767>

<!-- 则需要把Version.xml中的7.6.7.4改成大于等于pkg_version.xml的 force_update_le(7.6.7.6)-->
<?xml version="1.0" encoding="utf-8"?>
<root>
<alias>linux_767</alias>
<version>7.6.7.7</version>
<pkg>deb</pkg>
<arch>x64</arch>
</root>
```

**Comment by Hagb** [comment]
由于持久化的旧版本配置文件导致的这种现象已经被 https://github.com/Hagb/docker-easyconnect/commit/f4ef12f90b7a076ab1b7743de9887569e5ae277b 修复。
现在会自动应用新版配置文件了
