### ISSUE TITLE
与Clash TUN模式冲突

### ISSUE THREAD

**Issue by ywxt** [docker-easyconnect/docker-easyconnect#209]
使用Clash for Windows，开启TUN模式。

之后再启动docker，访问`1080`端口会报`Connection reset by peer`。

而在容器中是可以访问目的地址的。

- 系统： ArchLinux

**Comment by ywxt** [comment]
啓動Docker之前必須先要把Clash服務停掉纔行。

**Comment by Hagb** [comment]
能看看问题出现时宿主机的路由表和路由规则吗？（`ip route` 以及 `ip rule`）

**Comment by ywxt** [comment]
```
ip route
default via 192.168.1.20 dev wlo1 proto dhcp src 192.168.1.172 metric 20600
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
192.168.1.0/24 dev wlo1 proto kernel scope link src 192.168.1.172 metric 600
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1
```

```
ip rule
0:	from all lookup local
9500:	not from all dport 53 lookup main suppress_prefixlength 0
9510:	not from all iif lo lookup 1970566510
9520:	from 0.0.0.0 iif lo uidrange 0-4294967294 lookup 1970566510
9530:	from 198.18.0.1 iif lo uidrange 0-4294967294 lookup 1970566510
32766:	from all lookup main
32767:	from all lookup default
```

**Comment by ywxt** [comment]
```
ip rule
0:	from all lookup local
9500:	not from all dport 53 lookup main suppress_prefixlength 0
9510:	not from all iif lo lookup 1970566510
9520:	from 0.0.0.0 iif lo uidrange 0-4294967294 lookup 1970566510
9530:	from 198.18.0.1 iif lo uidrange 0-4294967294 lookup 1970566510
32766:	from all lookup main
32767:	from all lookup default

❯ ip route
default via 192.168.1.20 dev wlo1 proto dhcp src 192.168.1.172 metric 600
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
192.168.1.0/24 dev wlo1 proto kernel scope link src 192.168.1.172 metric 600
```

這是關閉Clash 之後的。

**Comment by Hagb** [comment]
看看 `ip route show table 1970566510`？

**Comment by ywxt** [comment]
```
❯ ip route show table 1970566510
default dev utun proto unspec
```

**Comment by Hagb** [comment]
> ```
> ❯ ip route show table 1970566510
> default dev utun proto unspec
> ```

看起来是 clash 的路由把通往 docker 的也覆盖了。试试跑一句  `ip route add 172.17.0.0/16 dev docker0 src 172.17.0.1 table 1970566510` 看看能不能好？

**Comment by ywxt** [comment]
不行，`ip route show table 1970566510` 顯示已經添加，但問題依舊。

**Comment by Hagb** [comment]
> 不行，`ip route show table 1970566510` 顯示已經添加，但問題依舊。

容器内 `busybox netstat -nl` 看看输出？（主要是看端口有没有开，虽然没有开导致的应该是 connection refused）

此外“访问1080端口会报Connection reset by peer”是指通过 1080 访问站点时 reset 还是指连接 1080 端口时 reset？（`ALL_PROXY=socks5://127.0.0.1:1080 curl 某个站点 -v` 和 `ALL_PROXY=socks5://172.17.0.2:1080 curl 某个站点 -v`看看输出？）

**Comment by ywxt** [comment]
好像是端口的問題，試了一下，HTTP代理可用。

```
❯ docker exec 2c45  busybox netstat -nl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:54530         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN
tcp        0      0 :::8888                 :::*                    LISTEN
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING      76727 /usr/share/sangfor/EasyConnect/resources/conf/ECDomainFile
```

```
❯ ALL_PROXY=socks5://127.0.0.1:1080 curl https://www.baidu.com -v
* Uses proxy env variable ALL_PROXY == 'socks5://127.0.0.1:1080'
*   Trying 127.0.0.1:1080...
* Connected to 127.0.0.1 (127.0.0.1) port 1080 (#0)
* Recv failure: 連線被對方重設
* Unable to receive initial SOCKS5 response.
* Closing connection 0
curl: (97) Recv failure: 連線被對方重設
```

不過此時，http比正常慢很多。

```
❯ curl -x http://localhost:8888  -o /dev/null -s -w "%{time_namelookup},%{time_connect}, \
%{time_starttransfer},%{time_total}, %{speed_download}" \
https://www.baidu.com && echo
0.000028,0.000124, 5.661949,5.704603, 428
```

正常情況：

```
❯ curl -x http://localhost:8888  -o /dev/null -s -w "%{time_namelookup},%{time_connect}, \
%{time_starttransfer},%{time_total}, %{speed_download}" \
https://www.baidu.com && echo
0.000021,0.000100, 0.203473,0.244282, 10000
```

**Comment by Hagb** [comment]
有点奇怪… 这个时候 EasyConnect 登录了吗？如果没有登录的话 socks5 服务不会启动（登录了的话应该会在 5 秒内启动），并且 http 代理走的也不是 EasyConnect

**Comment by ywxt** [comment]
```
❯ docker logs fab15b1c1520
WARNING: logging deactivated (can't log to stdout when daemonized)
auto login is disabled
user "xxx" login successfully!
svpn stop!
user "xxx" auto login successfully
```

應該是登錄了的。

**Comment by Hagb** [comment]
> 應該是登錄了的。

我在想有没有可能用了 `tun0` 外的网络界面（network interface）名。socks5 服务里面 `tun0` 是硬编码的

**Comment by ywxt** [comment]
> > 應該是登錄了的。
> 
> 我在想有没有可能用了 `tun0` 以外的网络界面（network interface）名。socks5 服务里面 `tun0` 是硬编码的

ifconfig 看起來沒有tun設備。

**Comment by Hagb** [comment]
> 啓動Docker之前必須先要把Clash服務停掉纔行。

那如果启动 Docker 之后再启动 Clash，Clash 服务能够运行吗？（宿主机有没有 Clash 的创建出来的 tun 设备）

**Comment by ywxt** [comment]
> > 啓動Docker之前必須先要把Clash服務停掉纔行。
> 
> 那如果启动 Docker 之后再启动 Clash，Clash 服务能够运行吗？（宿主机有没有 Clash 的创建出来的 tun 设备）

可以運行，停止Clash服務之後沒有tun設備。

**Comment by Hagb** [comment]
emmm… 有时间研究一下，看起来感觉像是 Clash 因为某种原因使得 EasyConnect 无法创建 tun 界面。如果方便的话可以提供一下容器里 `/usr/share/sangfor/EasyConnect/resources/logs` 中的日志（服务器、用户名、token 等信息注意脱敏）。
（我先睡了…）

**Comment by ywxt** [comment]
[](https://filetransfer.io/data-package/ukW0J4vs#link)

辛苦作者了。

**Comment by JHees** [comment]
我尝试了一下，在我的电脑上，clash的TUN模式与docker先后启动都不影响easyconnect创建tun0设备。

默认的TUN配置文件是代理所有ip的53端口的，冲突可能是由于默认配置导致回环问题。

我的解决方法是，需要将TUN配置文件中**DNS Hijacks**中默认的`any:53`改写为我所需要代理的ip池，如`192.168.0.0/16`。此时，TUN模式仅劫持所需ip交由clash处理，而不是所有ip。在这样设置下，我可以成功的让clash处理需要代理的ip地址，同时也不会干扰easyconnect登录

**Comment by jackpyd** [comment]
这是clash的问题，需要clash去解决。

**Comment by jackpyd** [comment]
就算是不用tun 模式，clash还是修改路由表，将本地的流量都转发到tun0

**Comment by jackpyd** [comment]
简单写了个shell脚本，尝试把指向tun0的转发规则都删除：

#!/bin/bash

IFS=$'\n'
for routeList in $(route -n); do
  mydes=$(echo $routeList | sed -n '/^172\.17\.0\./p')
  if [ $mydes ] >"172.17.0"; then
    iface=$(echo $mydes | awk '{print $8}')
    if [ $iface != 'docker0' ]; then
      net=$(echo $mydes | awk '{print $1}')
      netmask=$(echo $mydes | awk '{print $3}')
      sudo route del -net $net netmask $netmask
      echo "route del -net $net netmask $netmask"
    fi
  fi
done
IFS=$IFS.OLD

sudo route add  -net 172.17.0.0 netmask 255.255.254.0 dev docker0

**Comment by JHees** [comment]
duplicate of #184
