### ISSUE TITLE
关于硬件码的疑问

### ISSUE THREAD

**Issue by wrysunny** [docker-easyconnect/docker-easyconnect#246]
看了linux、android中的硬件码可以直接使用mac地址计算md5值得出，
而windows 貌似不能直接根据网卡mac地址计算MD5（直接计算出的值和预期结果不同）

我使用了虚拟机进行测试，只更改了虚拟机的mac地址 ，计算出来的硬件码和宿主机完全相同。
猜测windows下硬件码是mac地址加上固定的字符计算md5值

请问能讲讲windows中计算硬件码的具体的原理是啥？

**Comment by CTZZG** [comment]
根据深信服论坛信息[https://bbs.sangfor.com.cn/forum.php?mod=viewthread&tid=7696](url)，easyconnect取硬件特征码是有顺序的。
在老版本上是按照硬盘ID -> C盘ID ->D盘ID->E盘ID…
在新版本上是按照硬盘ID ->网卡mac ->C盘ID ->D盘ID->E盘ID...，且网卡MAC取的是具有默认路由的那个网卡的
前一步操作失败则进行下一步，即取硬盘ID失败，则取网卡mac...
因此在docker中只需保证MAC地址不变即可确保硬件码不变，而在windows中则需要确保硬盘ID不变，这也是为何电脑更换硬盘后需要重新提交硬件码的原因

**Comment by wrysunny** [comment]
@CTZZG  感谢解答
