### ISSUE TITLE
/usr/share/sangfor/EasyConnect/resources/conf/ECDomainFile domain socket connect failed, errno:2, errstr:No such file or directory.

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [docker-easyconnect/docker-easyconnect#285]
![image](https://github.com/Hagb/docker-easyconnect/assets/52443370/6893dcb9-bbde-4647-9fe1-e3c5acff5f67)
这个错误是正常现象吗？

**Comment by Hagb** [comment]
是的，登录过程中产生的是吧？

**Comment by bran-nie** [comment]
同样有这个提示，

不过，你启动 docker，登陆 easyconnect 后，可以访问内网吗

**Comment by Michaelzhouisnotwhite** [comment]
> 同样有这个提示，
> 
> 不过，你启动 docker，登陆 easyconnect 后，可以访问内网吗
> 

访问内网是什么意思，我现在这个vpn没办法用，不知道什么原因

**Comment by bran-nie** [comment]
> 访问内网是什么意思，我现在这个vpn没办法用，不知道什么原因

你现在已经可以在 VNC 提供的 web 端，登陆账号了吗（我的是证书登陆），我是已经登陆成功，但无法使用

**Comment by Michaelzhouisnotwhite** [comment]
> > 访问内网是什么意思，我现在这个vpn没办法用，不知道什么原因
> 
> 你现在已经可以在 VNC 提供的 web 端，登陆账号了吗（我的是证书登陆），我是已经登陆成功，但无法使用

可以，vnc也可以用，clash也配置成功了，也无法使用，相同的用户名和密码用docker cli显示用户名或者密码错误，但是ec登陆本地是可以的，不知道怎么排查问题

**Comment by Michaelzhouisnotwhite** [comment]
> 是的，登录过程中产生的是吧？

为什么图形界面可以正常登陆，cli却显示用户名和密码不正确呢？

**Comment by Michaelzhouisnotwhite** [comment]
一个电脑应该是可以打开多个ec-docker的吧，只要换掉端口就行吧

**Comment by bran-nie** [comment]
> 一个电脑应该是可以打开多个ec-docker的吧，只要换掉端口就行吧

你现在一个 ec-docker 可以工作了吗，

**Comment by l1teng** [comment]
> 是的，登录过程中产生的是吧？

我也有这个问题，是点击登录之后的报错。

**Comment by Michaelzhouisnotwhite** [comment]
> > 一个电脑应该是可以打开多个ec-docker的吧，只要换掉端口就行吧
> 
> 你现在一个 ec-docker 可以工作了吗，

可以，但是另一个不行

**Comment by l1teng** [comment]
> > > 一个电脑应该是可以打开多个ec-docker的吧，只要换掉端口就行吧
> > 
> > 
> > 你现在一个 ec-docker 可以工作了吗，
> 
> 可以，但是另一个不行

我的挂起来一个也是会出现 https://github.com/Hagb/docker-easyconnect/issues/285#issue-1854594411 这个问题，也是无法登录。想请教一下题主怎么解决的。

**Comment by l1teng** [comment]
我这边测试成功了，我在 _**同一个容器尝试了多次启动、关闭、重启，多次反复**_。

最终成功了。撒欢~

希望我的这个操作能够帮到还没成功的朋友。

!!! 抵制站在网络自由对立面的软件 !!!

**Comment by Akira-TL** [comment]
同样是这个情况，用web登录后每次都提示要更新，更完后提示登录成功，但没一会就显示这个，在过一会网页就出现注销成功了
