### ISSUE TITLE
可以考虑加入'--keep-alive'参数保持vpn链接吗

### ISSUE THREAD

**Issue by JHees** [docker-easyconnect/docker-easyconnect#304]
由于我对于登录esayconnect的过程感到麻烦，需要人机验证码以及接受手机短信。并且服务端会检测链接是否长时间没有操作。因此考虑到如下需求：

是否能在`docker run`中加入'--keep-alive <address> <interval time>'参数，每经过间隔时间向指定地址发送数据包实现保持vpn不被服务端断开。

我不知道这样的需求是否是必要的，或许我可以借助其他方法实现保持vpn链接吗？非常谢谢！

**Comment by Hagb** [comment]
试试 https://github.com/docker-easyconnect/docker-easyconnect/blob/master/doc/usage.md 中介绍的 `PING_ADDR`？

**Comment by JHees** [comment]
非常感谢，已经尝试过了。可惜也不能阻止vpn连接中断。我再试试看有什么别的办法

**Comment by JHees** [comment]
我检查了ip route，ping的ip确实不走tun0，我更改成路由表里的ip再试试。奇怪的是，这个ip是学校内网的服务器地址，我确实需要通过easyconnect才能访问服务器。但为什么他不走tun0呢

**Comment by Hagb** [comment]
> 我检查了ip route，ping的ip确实不走tun0，我更改成路由表里的ip再试试。奇怪的是，这个ip是学校内网的服务器地址，我确实需要通过easyconnect才能访问服务器。但为什么他不走tun0呢

你可以看看 `iptables -t nat -S SANGFOR_VIRTUAL` 的输出里面，有没有关于那个 ip 的转发规则

**Comment by JHees** [comment]
`# iptables -t nat -S SANGFOR_VIRTUAL
iptables: No chain/target/match by that name.`
似乎也不是

另外我们的vpn似乎不能使用ping来阻止断开连接，但如果维持rdp连接倒是可以。非常感谢
