### ISSUE TITLE
VNC配置成功，atrust登录成功，电脑仍无法访问公司内网

### ISSUE THREAD

**Issue by yxhblowally** [docker-easyconnect/docker-easyconnect#307]
@Hagb 您好，大佬

按照文档已经完成了总体流程的实现，但是浏览器访问公司内网仍然失败。

电脑设备信息如下：

系统：gentoo
docker：最新版
系统架构：amd64

使用场景：希望通过 docker 中的 atrust，可以让电脑访问公司内网

实现结果：在 vnc 中已经使用证书登陆成功，但在电脑浏览器中无法访问内网

具体的日志显示和相关信息查询：

![3](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/1f948caf-a853-43a4-8757-021e06673d6c)
![2](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/af6b5f24-5e3a-4fb6-b9b5-87e929ecba72)
![1](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/f5ad038c-f251-41cf-a506-547d27428ccc)

点击atrust页面的“网络检查”，出现如下结果：
![4](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/8f0c14d2-f34d-4525-84ab-3c98d2a15f52)
![5](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/c468cb83-9ea8-477d-80cb-f2fa10fa12d1)

点击atrust页面的“导出结果“，出现如下结果：

![6](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/cd342d01-d905-404c-93e4-91c14d2d856f)

麻烦您有时间看一下呢？非常感谢！！！！！！

**Comment by Hagb** [comment]
看看在容器中运行 `ip route` 和 `iptables-save` 的输出？
```
docker exec 容器名 ip route
docker exec 容器名 iptables-save
```

**Comment by yxhblowally** [comment]
> docker exec 容器名 ip route

![7](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/7aab489d-3348-4e5a-a961-33689c6ca0f8)
![8](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/d87bf70b-bf13-4be0-b803-876c6919a62e)

麻烦您看下呢

**Comment by Hagb** [comment]
看起来没啥问题的样子。
浏览器有没有设置代理？试试宿主机运行 `ALL_PROXY=socks5h://127.0.0.1:1080 curl -v 某个仅内网可访问的站点`？

**Comment by yxhblowally** [comment]
浏览器没有设置代码，运行后的结果如下：
![9](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/72e8ee55-16df-4354-b79a-a90d88ed97c5)

**Comment by Hagb** [comment]
> 浏览器没有设置代码，运行后的结果如下： ![9](https://user-images.githubusercontent.com/48521823/277629654-72e8ee55-16df-4354-b79a-a90d88ed97c5.png)

看起来是能访问到的

**Comment by yxhblowally** [comment]
但实际上是访问失败的
![11](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/a02df1e3-81da-443e-8967-7542c28e6902)

**Comment by yxhblowally** [comment]
> 看起来没啥问题的样子。 浏览器有没有设置代理？试试宿主机运行 `ALL_PROXY=socks5h://127.0.0.1:1080 curl -v 某个仅内网可访问的站点`？

有个疑问，因为之前是在docker里面运行的ip route和iptables-save, 所以是tun的存在的，但是我在宿主机里面走这两条命令，其实是没有tun存在的，所以是不是宿主机与docker之间并不存在数据传输的通道，导致无法访问公司内网呢？
如果真是这种情况的话，那宿主机到docker之间的数据通道应该怎么创建呢？

![12](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/ac16baeb-b607-438f-8e88-71dae3519f6e)
![13](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/6df5c375-c718-4f6c-84aa-75fd103c5724)

**Comment by yxhblowally** [comment]
谢谢大佬！！！！！！配置代理之后浏览器访问内网成功啦！！！！！！
但是有个问题哈，为什么宿主机上没有tun的数据通道呢？

**Comment by Hagb** [comment]
>  但是有个问题哈，为什么宿主机上没有tun的数据通道呢？

因为容器的网络是和宿主机隔离的

**Comment by yxhblowally** [comment]
谢谢大佬！！！！
我还想问一下，这个仅仅是浏览器开代理能访问到内网，如果系统想要安装访问公司内网的话，是不是也是需要设置代理呢？如果是这种情况的话，可不可以理解为任一系统在用docker启动容器的同时都需要设置系统的代理呢？

**Comment by Hagb** [comment]
>  我还想问一下，这个仅仅是浏览器开代理能访问到内网，如果系统想要安装访问公司内网的话，是不是也是需要设置代理呢？


“安装访问”意思是？别的地方要访问 aTrust 的网络确实也要设代理。

> 如果是这种情况的话，可不可以理解为任一系统在用docker启动容器的同时都需要设置系统的代理呢？

只是因为你需要用的代理是容器提供的。

**Comment by yxhblowally** [comment]
> “安装访问”意思是？别的地方要访问 aTrust 的网络确实也要设代理。

说错了，应该是系统想要访问公司内网（比如说电脑在外面需要通过登录atrust来访问公司网页） 

> 只是因为你需要用的代理是容器提供的。

按照我的理解哈，如果代理是容器提供的，那在容器起来后关掉浏览器的代理直接设备电脑的系统网络代理按理说应该也是可以访问内网的，但是我尝试了，关闭浏览器代理开启电脑系统网络代理后访问公司内网失败（电脑网络代理和浏览器代理配置是一样的）
![14](https://github.com/docker-easyconnect/docker-easyconnect/assets/48521823/38666262-5885-4082-91b9-2ec37b65c170)
麻烦问一下，我的理解是否正确呢？可不可以这样设置诶？

**Comment by Einskai** [comment]
> > “安装访问”意思是？别的地方要访问 aTrust 的网络确实也要设代理。
> 
> 说错了，应该是系统想要访问公司内网（比如说电脑在外面需要通过登录atrust来访问公司网页）
> 
> > 只是因为你需要用的代理是容器提供的。
> 
> 按照我的理解哈，如果代理是容器提供的，那在容器起来后关掉浏览器的代理直接设备电脑的系统网络代理按理说应该也是可以访问内网的，但是我尝试了，关闭浏览器代理开启电脑系统网络代理后访问公司内网失败（电脑网络代理和浏览器代理配置是一样的） ![14](https://user-images.githubusercontent.com/48521823/277852715-38666262-5885-4082-91b9-2ec37b65c170.png) 麻烦问一下，我的理解是否正确呢？可不可以这样设置诶？

注意截图的最下面橙色框的字，你系统设置了代理，但是浏览器不使用那个代理，所以浏览器还是无法访问内网。针对这个场景，你可以使用代理软件（例如clash）来吧本地的网络代理到docker上去。

**Comment by yxhblowally** [comment]
> 配置 socks 代理 127.0.0.1:1080，勾选“使用 SOCKS v5 时代理 DNS 查询”（更方便的发送可能是使用代理插件来管理代理）

大佬，麻烦问一下，我尝试在docker的daemon里面添加代理服务：

**Comment by yxhblowally** [comment]
> 配置 socks 代理 127.0.0.1:1080，勾选“使用 SOCKS v5 时代理 DNS 查询”（更方便的发送可能是使用代理插件来管理代理）

大佬，麻烦问一下，为了想实现启动docker的同时代理也自启动，我尝试在docker.service.d下创建了一个http-proxy.conf这个代理配置文件，然后在这个配置文件里面添加了sock5代理服务，具体代码如下：

[Service]
#Environment="ALL_PROXY=socks5h://127.0.0.1:1080/"   #这种格式也尝试过了，也是不行的
Environment="HTTP_PROXY=socks5://127.0.0.1:1080/"
Environment="HTTPS_PROXY=socks5://127.0.0.1:1080/"

然后重新加载了 daemon-reload 文件，也重启了docker，但是启动docker后代理未生效，这是什么原因呢？

另：直接尝试在命令行添加 -e HTTP_PROXY=socks5://127.0.0.1:1080 也未生效。

**Comment by JHees** [comment]
你好
这个解决方案应该是没有问题的，我就此issue询问了gpt，其建议可以尝试使用`systemctl status docker`检查docker是否正确加载了该配置文件。如果成功加载，命令输出中应该包含有`Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)`之类的信息。并且说`socks5h`多了个`h`

当然您也可以尝试使用 `echo $ALL_PROXY` 来直接查看系统变量是否被设置成功。

另外，需要提及的是，有的软件并不遵循系统代理。这意味着即便您成功的设置了系统代理，仍无法强制它们使用代理。虽然我不熟悉gentoo，但linux系统中可能也存在这个问题。
针对这样的问题，解决办法是您需要安装一个代理软件（如上面 @Hagb 提到的Clash）。他会安装一个虚拟网卡（或者是其他什么别的方式），代理电脑所有流量。之后您需要在代理软件上设置分流规则，将需要发送到内网的流量指向docker容器（即socks5://127.0.0.1:1080/)，而其他流量直接通过。当然您也可以选择将全局流量经docker容器都发送到公司内网，但这似乎失去了使用docker容器运行easyconnect的意义。这就取决于您了。

希望这能解决您的疑问，如果ok的话请关闭此issue。如果有新的问题可以提新的issue。:blush::blush:

**Comment by yxhblowally** [comment]
> 你好 这个解决方案应该是没有问题的，我就此issue询问了gpt，其建议可以尝试使用`systemctl status docker`检查docker是否正确加载了该配置文件。如果成功加载，命令输出中应该包含有`Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)`之类的信息。并且说`socks5h`多了个`h` 😆😆
> 
> 当然您也可以尝试使用 `echo $ALL_PROXY` 来直接查看系统变量是否被设置成功。
> 
> 另外，需要提及的是，有的软件并不遵循系统代理。这意味着即便您成功的设置了系统代理，仍无法强制它们使用代理。虽然我不熟悉gentoo，但linux系统中可能也存在这个问题。 针对这样的问题，解决办法是您需要安装一个代理软件（如上面 @Hagb 提到的Clash）。他会安装一个虚拟网卡（或者是其他什么别的方式），代理电脑所有流量。之后您需要在代理软件上设置分流规则，将需要发送到内网的流量指向docker容器（即socks5://127.0.0.1:1080/)，而其他流量直接通过。当然您也可以选择将全局流量经docker容器都发送到公司内网，但这似乎失去了使用docker容器运行easyconnect的意义。这就取决于您了。
> 
> 希望这能解决您的疑问，如果ok的话请关闭此issue。如果有新的问题可以提新的issue。😊😊

好的，谢谢你了哟
