### ISSUE TITLE
请问如何打包最新的 atrust

### ISSUE THREAD

**Issue by SuperHuangXu** [docker-easyconnect/docker-easyconnect#318]
<img width="1112" alt="image" src="https://github.com/docker-easyconnect/docker-easyconnect/assets/14816052/a03c9c8b-4bfb-420d-aad5-d5499131e661">
现在的 2.2.16 太旧了

**Comment by Hagb** [comment]
新版本 aTrust 的镜像已经生成并上传。尝试重新 pull 一下：
```bash
docker pull hagb/docker-atrust
```

**Comment by Hagb** [comment]
啊不对… 自动构建失败了，现在 dockerhub 上面还是旧的版本。我再去检查一下。

**Comment by SuperHuangXu** [comment]
> 啊不对… 自动构建失败了，现在 dockerhub 上面还是旧的版本。我再去检查一下。

麻烦你啦～
我想自己在本地打包，但是找不到最新包的链接，请问你是如何找到最新 atrust 版本的链接呀？

**Comment by Hagb** [comment]
> > 啊不对… 自动构建失败了，现在 dockerhub 上面还是旧的版本。我再去检查一下。
> 
> 麻烦你啦～ 我想自己在本地打包，但是找不到最新包的链接，请问你是如何找到最新 atrust 版本的链接呀？

参看 https://github.com/docker-easyconnect/docker-easyconnect/issues/275#issuecomment-1862406296 和 https://github.com/docker-easyconnect/docker-easyconnect/issues/275#issuecomment-1862411983

此外仓库 master 分支的 build-args/ 中的地址也已更新到最新版

**Comment by Hagb** [comment]
刚刚修复了 atrust 的构建并且推送到 docker hub 上了。尝试重新 pull 再运行看看行不行？

**Comment by SuperHuangXu** [comment]
> 刚刚修复了 atrust 的构建并且推送到 docker hub 上了。尝试重新 pull 再运行看看行不行？

可以正常使用了，感谢。

**Comment by ljyf5593** [comment]
现在新版已经到2.4，求大佬更新： 
https://atrustcdn.sangfor.com/standard/linux/2.4.10.40/uos/amd64/aTrustInstaller_amd64.deb

**Comment by zvictorliu** [comment]
同求最新版

**Comment by Hagb** [comment]
@ljyf5593 @zvictorliu 试试 pull 最新的 image？
