### ISSUE TITLE
登录成功后Clash日志显示SOCKS版本错误

### ISSUE THREAD

**Issue by Lucas04-nhr** [docker-easyconnect/docker-easyconnect#325]
能正常在Docker中登录，但是导入到Clash中时对于yaml文件中设置了经过代理路由的地址会reset，查看日志发现“SOCKS版本错误”。想知道这是因为我配置的原因还是学校的服务端不支持呢？

下面是日志的信息
```
[WARN] [TCP] dial failed error=SOCKS version error proxy=EasyConnect lAddr=127.0.0.1:56744 rAddr=vpn.hust.edu.cn:443 ru

le=DomainKeyword rulePayload=hust
```

下面是我的yaml文件，其中与代理配置有关的字段如下(由于不支持yaml格式文件的上传，我将后缀改为了txt)：
```
proxies:
   - { name: EasyConnect, type: socks5, server: 127.0.0.1, port: 5901}

```
[EasyConnect Config.yaml](https://github.com/docker-easyconnect/docker-easyconnect/files/14112795/EasyConnect.txt)

**Comment by Lucas04-nhr** [comment]
部署容器时使用的命令是
```
docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=041104 -e DISABLE_PKG_VERSION_XML=1 -v $HOME/.ecdata:/root -p 127.0.0.1:5901:5901 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:7.6.7
```

**Comment by Lucas04-nhr** [comment]
感谢指点，按照您给出的两点进行逐一排查：
1. 我的```external-controller```端口并非有意为之，故将此行注释掉之后再进行尝试；
2. 将连接学校VPN的URL(```vpn.hust.edu.cn```)设置为```DIRECT```；
3. 为避免其他规则干扰，我删去了规则文件中所有其他```DIRECT```规则的部分，仅保留```REJECT```部分。

现在Clash给出的日志中```vpn.hust.edu.cn```可正常走```DIRECT```进行通信，但是我测试得到中国知网相关网址仍然出现前述报错：
```
[WARN] [TCP] dial failed error=SOCKS version error proxy=EasyConnect lAddr=127.0.0.1:56744 rAddr=vpn.hust.edu.cn:443 rule=DomainKeyword rulePayload=cnki
```

浏览器则提示“```ERR_CONNECTION_RESET```”，即连接被重置。

附：
经过更改之后我的[配置文件](https://github.com/docker-easyconnect/docker-easyconnect/files/14177267/EasyConnect.txt)相关部分如下：
```yaml

# external-controller: '127.0.0.1:1080'

   - { name: EasyConnect, type: socks5, server: 127.0.0.1, port: 5901}
rules:
    - 'DOMAIN-KEYWORD,cnki,EasyConnect'
    - 'DOMAIN-KEYWORD,wanfangdata,EasyConnect'
    - 'DOMAIN-KEYWORD,google,EasyConnect'
    - 'DOMAIN,222.20.95.79,EasyConnect'
    - 'DOMAIN,injections.adguard.org,DIRECT'
    - 'DOMAIN,local.adguard.org,DIRECT'
    - 'DOMAIN,vpn.hust.edu.cn,DIRECT'
    - 'DOMAIN-SUFFIX,local,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'IP-CIDR,224.0.0.0/4,DIRECT'
    - 'IP-CIDR6,fe80::/10,DIRECT'
```

**Comment by JHees** [comment]
那看来和controller并没有关系。

请问你是否有查询过clash中的connection（或者其他网络工具），访问网站时连接数有没有持续增多呢？这样可以确切的排除回环问题。

另外，我学校的vpn并不仅仅访问vpn.*.edu.cn这一地址，因此我将clash规则配置为docker全走direct 
```
- PROCESS-NAME,*.docker.*,DIRECT
```

连接被重置一般是连接链路中的某一环出现了问题。（比如说我曾经经历过firefox无法打开的网站但换edge就可以了。）我能想到的其他原因可能是由于学校服务器端只对特定的网站提供响应，但这可能性比较低也不好排查

我可能只能想到这么多信息了，希望对你是有帮助的

**Comment by Lucas04-nhr** [comment]
我刚刚逐行排查了一下，发现是端口配置错误，我的Docker配置时命令行设置了两个端口用于接收本地想转发至VPN的连接(`1080`和`5901`)。但是`yaml`文件中的端口设置成`5901`，按理来讲是没问题的，但估计是我手上这版ClashX的bug(?)，我将端口改成`1080`就可以完美解决了。

附：出问题的配置：
```yaml
proxies:
   - { name: EasyConnect, type: socks5, server: 127.0.0.1, port: 5901}
````

将其更改为
```yaml
proxies:
   - { name: EasyConnect, type: socks5, server: 127.0.0.1, port: 1080}
````
即可解决。
