### ISSUE TITLE
容器 无法正常运行 报错如下

### ISSUE THREAD

**Issue by renoyuan** [docker-easyconnect/docker-easyconnect#336]
纯命令行版本
ker-easyconnect:cli
Error: ipv4: FIB table does not exist.
Flush terminated
Error: Missing goto target for action goto.
/usr/local/bin/start.sh: line 146: tigervncpasswd: command not found
WARNING: logging deactivated (can't log to stdout when daemonized)
/usr/local/bin/start.sh: line 152: tigervncserver: command not found
/usr/local/bin/start.sh: line 164: xclip: command not found
auto login is disabled

**Comment by renoyuan** [comment]
已解决是我配置参数的问题，好用这个仓库

**Comment by Cache1geT** [comment]
> 已解决是我配置参数的问题，好用这个仓库

你好，请问是哪个参数的问题呢。和你遇到了同样的报错

**Comment by renoyuan** [comment]
docker run --rm --device /dev/net/tun --cap-add NET_ADMIN -ti  -p 127.0.0.1:1080:1080 -p 127.0.0.1:8888:8888 -e EC_VER=7.6.7 -e CLI_OPTS="-d vpn_host -u user -p pwd" hagb/docker-easyconnect:cli“ 
确认下CLI_OPTS传入的vpn 账号信息是不是对的
