### ISSUE TITLE
hagb/docker-atrust 最新版(fc1c882180ff) 提示DNS hijacking is disabled，无法正常解析域名

### ISSUE THREAD

**Issue by dozer47528** [docker-easyconnect/docker-easyconnect#352]
image id: fc1c882180ff
操作系统: macOS 14.5 (23F79)
Docker: OrbStack

![CleanShot 2024-05-15 at 10 05 01](https://github.com/docker-easyconnect/docker-easyconnect/assets/1676951/05c2c375-fbd0-49c0-9cbf-82a8596b25dd)

同样的启动参数，用老版本(f3e8630c0524) 就没问题

**Comment by LamontLiao** [comment]
您好，我想向您请教一些问题，我同样使用OrbStack，系统版本跟您一样，M3Pro版本，遇到的问题是，我可以连接上容器内的VNC服务，可以使用本机浏览器，正常登陆，VNC看到容器内也正常登陆完成。代理使用的是clash，socks5代理是可以正常ping通，在访问公司内网的时候，能看到是能够和公司服务器握手成功的，但是宿主机一直连接超时，收不到来自公司服务器的数据。在这里想向您讨教一下您的设置参数，我参考一下

**Comment by Hagb** [comment]
目前我没有能使用的 atrust 帐号。如果有人能借我一个的话（我邮箱 hagb_green@qq.com 。亦可可加密后发给我，我的 OpenPGP 密钥在 https://hagb.name/key.asc ），我这周末可以尝试看看。

**Comment by hu516** [comment]
同样的问题，win10，域名无法解析
![image](https://github.com/docker-easyconnect/docker-easyconnect/assets/21280642/c11289eb-4911-4e45-98bc-3991d491787a)

**Comment by TurnOffNOD** [comment]
> 可能和 [#274 (comment)](https://github.com/docker-easyconnect/docker-easyconnect/issues/274#issuecomment-2103027350) 是同一个问题。目前我没有能使用的 atrust 帐号。如果有人能借我一个的话（我邮箱 [hagb_green@qq.com](mailto:hagb_green@qq.com) 。亦可可加密后发给我，我的 OpenPGP 密钥在 https://hagb.name/key.asc ），我这周末可以尝试看看。 CC @TurnOffNOD

我现在还没有自己的aTrust帐号……

**Comment by hu516** [comment]
加上这个启动参数试试 --sysctl net.ipv4.conf.default.route_localnet=1

**Comment by Hagb** [comment]
已经在 https://github.com/docker-easyconnect/docker-easyconnect/commit/75fb271bd558c5678b5e54f611a7da019c16de87 修复。请重新 pull 最新镜像（`docker pull hagb/atrust`），并在运行时加上参数 `--sysctl net.ipv4.conf.default.route_localnet=1`.
