### ISSUE TITLE
容器环境下，无法使用域名访问代理服务

### ISSUE THREAD

**Issue by seedscoder** [docker-easyconnect/docker-easyconnect#359]
现象：在直接下载 aTrust 客户端的情况下，可以直接访问域名对应的服务，但是通过 docker-compose 搭建的服务，访问域名就出现异常了

> docker-compose.yml 如下：

```xml
version: '3.5'
services:
  easyconnect:
    image: hagb/docker-atrust:latest
    ports:
      - 5901:5901
      - 51080:1080
      - 54631:54631
      - 58888:8888
    volumes:
      - /Users/me/workspace/data/docker/ecdata:/root
    environment:
      URLWIN: 1
      PASSWORD: abc1234Abc
      DISABLE_PKG_VERSION_XML: 1
      CLIP_TEXT: Yq85NCCn
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN

```

我想使用 Clash For Windows 转发，局域网IP可以正常访问，但是公网域名访问就出现异常了。并且一直刷日志，这是什么原因？，配置有甚么问题吗？

![xxx](https://github.com/docker-easyconnect/docker-easyconnect/assets/34568397/41ad0eee-65f3-4051-9d85-0769bb2c3b20)

使用域名访问就一直打印这个日志，并且无法正常访问

![yyyy](https://github.com/docker-easyconnect/docker-easyconnect/assets/34568397/f65eb124-b941-46e1-b4b1-050fdf94a78a)

**Comment by EdenBob** [comment]
请问大佬是如何解决的呢，我貌似也碰到这个问题了

**Comment by seedscoder** [comment]
> 请问大佬是如何解决的呢，我貌似也碰到这个问题了

尝试使用最新版

**Comment by EdenBob** [comment]
> > 请问大佬是如何解决的呢，我貌似也碰到这个问题了
> 
> 尝试使用最新版

确实 作者已经在最新版里修复了此问题  现在可以完美使用了
