### ISSUE TITLE
根据Dockerfile自行本地编译了新版aTrust，但是打开能显示界面，但是很快就提示服务无法启动

### ISSUE THREAD

**Issue by tlju** [docker-easyconnect/docker-easyconnect#363]
公司最近升级了新版aTrust，登录了就禁用本地网络只能使用VPN网络，就很麻烦，自行编译新版也没办法使用，麻烦帮忙看下，下载的新版aTrust地址：
https://musetransfer.com/s/lktnwefmm
请点击链接获取《无主题 - aTrustInstaller_amd64.deb》, 有效期至7月10日

**Comment by Hagb** [comment]
看看在宿主机 `echo $DOCKER_HOST` 看看指向的文件是否是 `podman.sock`？
此外，（不管上一个问题的回答是什么）尝试从 [develop](https://github.com/docker-easyconnect/docker-easyconnect/tree/develop) 分支 (71f1b24) 构建？这个 commit 很可能修复了 podman 下 aTrust 的运行。构建方式和 master 的相同，除了 clone 的时候需要指定 develop 分支（亦可在现有本地仓库的基础上 `git fetch --all; git checkout origin/develop`）。

**Comment by tlju** [comment]
`echo $DOCKER_HOST`显示为空，宿主机是Alpine Linux v3.20，重新用develop分支编译后还是报错无法连接。log主要日志如下：
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
log isn't inited.[aTrustAgent][getUserHomePath:288]pw_name:root,pw_dir:/root
[current process id:7532] lockfile path:/usr/share/sangfor/.aTrust/sapp-aTrustAgent-b269-lockfile
log isn't inited.[aTrustAgent][getUserHomePath:288]pw_name:sangfor,pw_dir:/home/sangfor
[current process id:7563] lockfile path:/usr/share/sangfor/.aTrust/sapp-aTrustAgent_plugins_aTrustCore_h_e-5c4f-lockfile
full path of server:/usr/share/sangfor/.aTrust/sapp-aTrustAgent_plugins_aTrustCore_h_e-5c4f
Thrift: Mon Jul  8 13:55:12 2024 TNonblockingServer: Serving with 1 io threads.
Thrift: Mon Jul  8 13:55:12 2024 TNonblockingServer: using libevent 2.1.12-stable method epoll
Thrift: Mon Jul  8 13:55:12 2024 TNonblocking: IO thread #0 registered for listen.
Thrift: Mon Jul  8 13:55:12 2024 TNonblocking: IO thread #0 registered for notify.
Thrift: Mon Jul  8 13:55:12 2024 TNonblockingServer: IO thread #0 entering loop...
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory

(process:7563): GLib-GObject-WARNING **: 13:55:13.403: invalid (NULL) pointer instance

(process:7563): GLib-GObject-CRITICAL **: 13:55:13.404: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
basic_string::_M_construct null not valid
basic information:
time:2024-07-08 13:55:13.409 pid:7563 tid:140152340899520
msg: 'basic_string::_M_construct null not valid'
if you want know the detail of assert,please check log
Fatal in File: /home/jenkins/13/cs_gitlab/749/src/EAIOSDKWrapper/ModuleInstance.cpp, Line: 203, Function: virtual const char* ModuleInstance::moduleCapacities()
Expression: 'false' failed

**Comment by Hagb** [comment]
> 重新用develop分支编译后还是报错无法连接
更具体的现象是？
1. VNC 能使用吗？
2. 能登录吗？会提示服务无法启动吗？
3. 登录之后能连接内网吗？
4. 有没有其他异常现象？

> 启动docker-compose.yml配置如下：

可以试试先 `docker run` 调通之后再写成 docker-compose.yml.
参看 https://github.com/docker-easyconnect/docker-easyconnect/tree/develop#%E5%9B%BE%E5%BD%A2%E7%95%8C%E9%9D%A2%E7%89%88-atrustamd64arm64mips64el-%E6%9E%B6%E6%9E%84 。develop 分支运行时注意加上 `--sysctl net.ipv4.conf.default.route_localnet=1` 参数，该选项在 develop 复制可以修复 aTrust 的 DNS 解析问题。

此外，目前 `develop` 分支的内容已经 push 到 dockerhub，可以尝试使用 `hagb/docker-atrust:dev` 镜像（`docker pull hagb/docker-atrust:dev`，之后启动时镜像名里也要加上 `:dev` 的 tag）

**Comment by tlju** [comment]
根据最新develop分支本地编译成功，可以正常使用，感谢大佬
