### ISSUE TITLE
请教docker启动参数如何配置MAC地址，如何定时访问特定URL保持VPN在线

### ISSUE THREAD

**Issue by tlju** [docker-easyconnect/docker-easyconnect#366]
启动命令如下：
docker run --rm --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -e URLWIN=1 -e FAKE_HWADDR=27-0B-F8-71-3C-6C -e PING_ADDR=https://192.168.112.20:8444 -v $HOME/.atrust-data:/root -p 0.0.0.0:5901:5901 -p 127.0.0.1:1080:1080 -p 127.0.0.1:8888:8888 -p 127.0.0.1:54631:54631 --sysctl net.ipv4.conf.default.route_localnet=1 hagb/docker-atrust

进入容器内发现没有变更mac地址，PING_ADDR好像也不生效

**Comment by Hagb** [comment]
> PING_ADDR好像也不生效

不带端口号、不带（应用层）协议名。就是单纯 `192.168.112.20`，通过 icmp 协议（网络层）来 ping 的. 可以用 `ip route get 192.168.112.20` 确认一下 atrust 对这个 ip 是不是做三层代理。

> 进入容器内发现没有变更mac地址

这里具体如何看的？这个 mac 地址的 hook 仅对 vpn（atrust/easyconnect）生效，不对容器内其他程序生效。
