### ISSUE TITLE
登陆被atrust客户端检测拦截

### ISSUE THREAD

**Issue by xidongting** [docker-easyconnect/docker-easyconnect#410]
启动atrust docker后，打开登陆页面，扫码登陆，得到如下提示：
<img width="658" alt="image" src="https://github.com/user-attachments/assets/0aed35e1-9a0e-417c-acb3-be95cfd4bf4a">

观察到登陆页面上，发起了很多detect请求，如下：
```
https://localhost.sangfor.com.cn:54631/v1/detect
https://localhost.sangfor.com.cn:54642/v1/detect
https://127.0.0.1:54630/v1/detect
……
```

----------

得把整个546xx端口段全部映射出来才行

**Comment by Einskai** [comment]
如果我的推测没错的话，应该不需要把整个546xx端口段全部映射出来，那个web有一组端口，他会一次去尝试里面的端口能不能用，所以理论上你只需要映射出一个在列表里面的端口就可以了？起码同个公司出的easyconnect是这样的。
